# 引入 not-pure-poole 主题
plugins:
  - jekyll-remote-theme
remote_theme: vszhub/not-pure-poole

# 网站基本信息设置
title: Tao Wang (王涛)
url: "https://wangtao-phy.github.io" 

description: Theoretical Physics Researcher
